name: ssh build OpenWrt WNDR4300V1
on: push
    
jobs:
  build:
    runs-on: ubuntu-16.04 #ubuntu-latest #ubuntu-18.04 #
    steps:
    - name: 系统环境更新、清理空间 | Installation depends
      run: |
          sudo apt-get update
          sudo timedatectl set-timezone "Asia/Shanghai"
          alias ll="ls -ahl"
        
    - name: SSH 连接
      uses: mxschmitt/action-tmate@v1
